#!/bin/bash
#: Title	: hw
#: Date		: 02/02/2018
#: Author	: Jameel Aslam <jameel.aslam@trapezegroup.com.au>
#: Version	: 1.0
#: Description	: print Hello, World!
#: Options	: None

printf "%s\n" "Hello, World!"
